language: r
cache: packages

r: 
  - oldrel
  - release
  - devel
  
before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true

  
notifications:
  email:
    on_succes: change
    on_failure: change
    recipients: 
      - rsbr@novonordisk.com
      
git:
  depth: 3 ##false ##if set to false then only the current commit will be synced